#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'git'
cookbook 'lxmx_hostname'
cookbook 'locale'
cookbook 'user'
cookbook 'nginx'
cookbook 'mysql'
cookbook 'database'
cookbook 'mysqldatabases', :git => "https://github.com/macovsky/chef-mysqldatabases"
cookbook 'imagemagick'
cookbook 'openssh'
cookbook 'jolicode-php', :git => 'https://github.com/jolicode/chef-cookbook-php.git'
cookbook 'postgresql', :git => 'https://github.com/hw-cookbooks/postgresql'
cookbook 'newrelic'
cookbook "wkhtmltopdf", :git => 'https://github.com/bflad/chef-wkhtmltopdf'