#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'hostname'
cookbook 'locale'
cookbook 'user'
cookbook 'nginx'
cookbook 'unicorn', :git => 'https://github.com/macovsky/chef-unicorn'
cookbook 'rails', :git => 'https://github.com/macovsky/chef-rails'
cookbook 'mysql'
cookbook 'imagemagick'
