#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'hostname'
cookbook 'locale'
cookbook 'user'
cookbook 'nginx'
cookbook 'rails', "0.4.0", :git => "https://github.com/macovsky/chef-rails"
cookbook 'mysql'
cookbook 'database'
cookbook 'mysqldatabases', :git => "https://github.com/macovsky/chef-mysqldatabases"
cookbook 'imagemagick'
cookbook 'openssh'
